LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

PACKAGE MEMORY_TYPES IS

CONSTANT C_DBUS_WIDTH : POSITIVE := 8;
CONSTANT C_ABUS_WIDTH : POSITIVE := 4;

CONSTANT C_DBUS_MSB   : NATURAL  := C_DBUS_WIDTH-1;
CONSTANT C_ABUS_MSB   : NATURAL  := C_ABUS_WIDTH-1;

SUBTYPE DBUS_t IS UNSIGNED(C_DBUS_MSB DOWNTO 0);
SUBTYPE ABUS_t IS UNSIGNED(C_ABUS_MSB DOWNTO 0);
TYPE MEMORY_T IS ARRAY(0 TO 2**C_ABUS_WIDTH - 1) OF DBUS_t;

END PACKAGE MEMORY_TYPES;

PACKAGE BODY MEMORY_TYPES IS
END PACKAGE BODY MEMORY_TYPES;
