LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

LIBRARY GENERAL;
USE GENERAL.MEMORY_TYPES.C_DBUS_MSB;
USE GENERAL.MEMORY_TYPES.C_ABUS_MSB;
USE GENERAL.MEMORY_TYPES.MEMORY_T;

ENTITY MEMORY IS
    PORT (
        SIGNAL CLK    : IN  STD_LOGIC;
        SIGNAL RST    : IN  STD_LOGIC;
        SIGNAL CLR    : IN  STD_LOGIC;
        SIGNAL WE     : IN  STD_LOGIC;
        SIGNAL WADDR  : IN  UNSIGNED(C_ABUS_MSB DOWNTO 0);
        SIGNAL WDATA  : IN  UNSIGNED(C_DBUS_MSB DOWNTO 0);
        SIGNAL RADDR0 : IN  UNSIGNED(C_ABUS_MSB DOWNTO 0);
        SIGNAL RDATA0 : OUT UNSIGNED(C_DBUS_MSB DOWNTO 0);
        SIGNAL RADDR1 : IN  UNSIGNED(C_ABUS_MSB DOWNTO 0);
        SIGNAL RDATA1 : OUT UNSIGNED(C_DBUS_MSB DOWNTO 0)
    );
END ENTITY MEMORY;

ARCHITECTURE RTL OF MEMORY IS
    SIGNAL S_MEM : MEMORY_T;
BEGIN

    PROCESS(CLK, RST)
    BEGIN
        IF RST = '1' THEN
            S_MEM <= (OTHERS => (OTHERS => '0'));
        ELSIF RISING_EDGE(CLK) THEN
            IF CLR = '1' THEN
                S_MEM <= (OTHERS => (OTHERS => '0'));
            ELSIF WE = '1' THEN
                S_MEM(TO_INTEGER(WADDR)) <= WDATA;
            END IF;
        END IF;
    END PROCESS;

    RDATA0 <= S_MEM(TO_INTEGER(RADDR0));
    RDATA1 <= S_MEM(TO_INTEGER(RADDR1));

END ARCHITECTURE RTL;
