
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

------------------------------------------------------------------


PACKAGE UTILITIES IS
  TYPE POSITIVE_VECTOR_t IS ARRAY (NATURAL RANGE <>) OF POSITIVE;

	-- DEVUELVE EL NUMERO DE BITS NECESARIOS PARA REPRESENTAR 'ARG' EN BINARIO NATURAL.
	-- EQUIVALE A FLOOR(LOG2(ARG)) + 1.
	-- EJEMPLOS: CLOG2(1)=1, CLOG2(2)=2, CLOG2(3)=2, CLOG2(4)=3, CLOG2(5)=3
	PURE FUNCTION CLOG2 (CONSTANT ARG : POSITIVE) RETURN POSITIVE;
	
  -- MAXIMO COMUN DIVISOR (ALGORITMO DE EUCLIDES)
  PURE FUNCTION GCD (CONSTANT A, B : POSITIVE) RETURN POSITIVE;
  PURE FUNCTION GCD_ARRAY (CONSTANT V : POSITIVE_VECTOR_t) RETURN POSITIVE;
  PURE FUNCTION MAX_IN_ARRAY (CONSTANT V : POSITIVE_VECTOR_t) RETURN POSITIVE;
  PURE FUNCTION DIV_ARRAY (CONSTANT V : POSITIVE_VECTOR_t; CONSTANT DIV : POSITIVE) RETURN POSITIVE_VECTOR_t;
	
	PURE FUNCTION TO_SLV(SIGNAL ARG: IN UNSIGNED) RETURN STD_LOGIC_VECTOR;
	PURE FUNCTION CONCAT(SIGNAL ARG_H, ARG_L: IN UNSIGNED) RETURN STD_LOGIC_VECTOR;

END PACKAGE UTILITIES;


------------------------------------------------------------------


PACKAGE BODY UTILITIES IS

-- CUENTA CUANTAS VECES SE PUEDE DIVIDIR 'ARG' ENTRE 2 HASTA LLEGAR A 1.
-- CADA DIVISION REPRESENTA UN BIT: AL TERMINAR, RET CONTIENE EL ANCHO MINIMO
-- DEL BUS (NUMERO DE BITS) PARA ALBERGAR 'ARG' EN BINARIO NATURAL.
PURE FUNCTION CLOG2 (CONSTANT ARG : POSITIVE) RETURN POSITIVE IS

	VARIABLE RET : POSITIVE := 1; -- ANCHO ACUMULADO (MINIMO 1 BIT)
	VARIABLE ACC : POSITIVE := ARG; -- COPIA DE TRABAJO DEL ARGUMENTO

BEGIN

  -- DIVIDE ACC ENTRE 2 EN CADA ITERACION (DIVISION ENTERA).
  -- CADA PASO EQUIVALE A DESPLAZAR UN BIT A LA DERECHA.
  -- EL BUCLE TERMINA CUANDO ACC LLEGA A 1 (UN SOLO BIT).
  WHILE (ACC > 1) LOOP
    ACC := ACC / 2;
    RET := RET + 1;
  END LOOP;

  RETURN RET;

END FUNCTION CLOG2;

PURE FUNCTION GCD (CONSTANT A, B : POSITIVE) RETURN POSITIVE IS
  VARIABLE X : NATURAL := A;
  VARIABLE Y : NATURAL := B;
  VARIABLE T : NATURAL;
BEGIN
  WHILE Y /= 0 LOOP
    T := X MOD Y;
    X := Y;
    Y := T;
  END LOOP;

  RETURN POSITIVE(X);
END FUNCTION GCD;

PURE FUNCTION GCD_ARRAY (CONSTANT V : POSITIVE_VECTOR_t) RETURN POSITIVE IS
  VARIABLE RET : POSITIVE := V(V'LOW);
BEGIN
  FOR I IN (V'LOW + 1) TO V'HIGH LOOP
    RET := GCD(RET, V(I));
  END LOOP;

  RETURN RET;
END FUNCTION GCD_ARRAY;

PURE FUNCTION MAX_IN_ARRAY (CONSTANT V : POSITIVE_VECTOR_t) RETURN POSITIVE IS
  VARIABLE RET : POSITIVE := V(V'LOW);
BEGIN
  FOR I IN (V'LOW + 1) TO V'HIGH LOOP
    IF V(I) > RET THEN
      RET := V(I);
    END IF;
  END LOOP;

  RETURN RET;
END FUNCTION MAX_IN_ARRAY;

PURE FUNCTION DIV_ARRAY (CONSTANT V : POSITIVE_VECTOR_t; CONSTANT DIV : POSITIVE) RETURN POSITIVE_VECTOR_t IS
  VARIABLE RET : POSITIVE_VECTOR_t(V'RANGE);
BEGIN
  FOR I IN V'RANGE LOOP
    RET(I) := V(I) / DIV;
  END LOOP;

  RETURN RET;
END FUNCTION DIV_ARRAY;

PURE FUNCTION TO_SLV(SIGNAL ARG: IN UNSIGNED) RETURN STD_LOGIC_VECTOR IS
BEGIN
   RETURN STD_LOGIC_VECTOR(ARG);
END FUNCTION TO_SLV;

PURE FUNCTION CONCAT(SIGNAL ARG_H, ARG_L: IN UNSIGNED) RETURN STD_LOGIC_VECTOR IS
BEGIN
   RETURN (TO_SLV(ARG_H) & TO_SLV(ARG_L));
END FUNCTION CONCAT;

END PACKAGE BODY UTILITIES;
